image:
  file: .gitpod.Dockerfile
tasks:
  - name: Startup
    command: sh ./config/startup.sh
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - zhuangtongfa.material-theme
    - bmewburn.vscode-intelephense-client
ports:
    # Automically open Apache site
  - port: 8001
    onOpen: open-browser
  - port: 33060
    onOpen: ignore
  - port: 3306
    onOpen: ignore
